      - name: Commit and push if changed (DEBUG)
        run: |
          # Her komutu ve çıktısını detaylı görmek için verbose modunu aç
          set -x

          echo "--- Başlangıç Durumu ---"
          git status
          git branch -v
          git remote -v
          
          echo "--- Dosya Kontrolü ---"
          if [ ! -f "inat.txt" ]; then
            echo "HATA: inat.txt dosyası bulunamadı. Script dosyayı oluşturmamış."
            exit 1
          fi
          echo "inat.txt dosyası mevcut."

          # Git'in değişikliği görüp görmediğini kontrol et
          if ! git status --porcelain | grep -q "inat.txt"; then
            echo "UYARI: Git'e göre inat.txt dosyasında bir değişiklik yok. Mevcut dosya ile aynı olabilir."
            echo "--- Dosya içeriği ---"
            cat inat.txt
            exit 0
          fi
          echo "Git tarafından değişiklikler algılandı."

          echo "--- Git Yapılandırması ---"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          echo "--- Son Değişiklikleri Çekme (pull) ---"
          git pull --rebase

          echo "--- Dosyayı Ekleme (add) ---"
          git add inat.txt
          git status
          
          echo "--- Commit Oluşturma ---"
          git commit -m "Update inat.txt [skip ci]"

          echo "--- Uzak Sunucuya Gönderme (push) ---"
          # Sorunun yaşandığı kritik komut bu. Çıktısı çok önemli.
          git push

          echo "--- İşlem Tamamlandı ---"
          
